seed: 42
output_dir: "output"

wandb:
  enabled: true
  project: "ditto"
  name: "SmolLM3-3B_uditto_author0" #"ministral8binstruct_ditto"
  group: "ditto"
  tags: ["smollm3", "3b", "author_1", "MSP"]
  notes: "UDITTO MSP training on HuggingFaceTB/SmolLM3-3B" #"DITTO training on Ministral-8B-Instruct-2410"

lora:
  r: 16
  lora_alpha: 32
  lora_dropout: 0.05
  target_modules:
    - q_proj
    - k_proj
    - v_proj
    - o_proj
    - gate_proj
    - down_proj
    - up_proj

model:
  adapter_name: "ditto"
  device: "cuda"
  attn_implementation: "flash_attention_2"
  name_or_path: "HuggingFaceTB/SmolLM3-3B"
  use_bf16: true

dataset:
  name_or_path: "belati/ccat50"
  batch_size: 2 # device_batch * rescale_batch = 2 * 2
  max_length: 1024
  num_workers: 0

  author_id: 0
  train_samples_per_author: 10
  eval_samples_per_author: 3

training_args:
  max_grad_norm: 1.0
  max_steps: 1000
  warmup_steps: 100
  learning_rate: 5.0e-5 # x10 learning rate for LoRA, default was 5e-6
  weight_decay: 0.01

sampler:
  resample_rate: 50
  frac_expert: 0.7
  frac_replay: 0.2
  frac_noisy: 0.1
  rescale_batch: 2
  bootstrap_count: 4
