defaults:
  - model: mistral-7b
  - _self_

seed: 42

push_to_hub: false

hydra:
  run:
    dir: outputs/models/${dataset.name}_${dataset.author_id}_${model.name}
  sweep:
    dir: outputs/models
    subdir: ${dataset.name}_${dataset.author_id}_${model.name}

wandb:
  enabled: false
  project: "uditto"
  name: ${dataset.name}_${dataset.author_id}_${model.name}
  group: "ditto"

lora:
  r: 16
  lora_alpha: 64
  lora_dropout: 0.05
  target_modules:
    - q_proj
    - k_proj
    - v_proj
    - o_proj
    - gate_proj
    - down_proj
    - up_proj

dataset:
  name: ccat50
  name_or_path: "belati/ccat50"
  num_workers: 0

  author_id: 0
  train_samples_per_author: 7
  eval_samples_per_author: 3

training_args:
  general:
    max_grad_norm: 1.0
  sft:
    warmup_steps: 10
    max_steps: 100
    max_length: 2048
    per_device_train_batch_size: 8
    padding_free: true
  dpo:
    warmup_steps: 10
    max_steps: 40
    max_length: 1024
    gradient_checkpointing: true
    per_device_train_batch_size: 4
    gradient_accumulation_steps: 1
    padding_free: true

optim_args:
  sft:
    lr: 2.0e-4 # x10 because of LoRA
    weight_decay: 0
  dpo:
    lr: 5.0e-5 # x10 because of LoRA
    weight_decay: 0

sampler:
  resample_rate: 10
  frac_expert: 0.675
  frac_replay: 0.25
  frac_noisy: 0.125
  rescale_batch: 2

  gen_kwargs:
    do_sample: true
    max_length: 1024
    num_return_sequences: 4
    temperature: 1.2
    repetition_penalty: 1.1
    cache_implementation: offloaded
