seed: 42

hydra:
  run:
    dir: outputs/models/${dataset.name}_${dataset.author_id}_${model.name}


wandb:
  enabled: true
  project: "sanity-check"
  name: ${dataset.name}_${dataset.author_id}_${model.name}
  group: "ditto"
  tags: ["smollm3", "3b", "author_1", "MSP"]
  notes: "UDITTO MSP training on HuggingFaceTB/SmolLM3-3B" #"DITTO training on Ministral-8B-Instruct-2410"

lora:
  r: 16
  lora_alpha: 32
  lora_dropout: 0.05
  target_modules:
    - q_proj
    - k_proj
    - v_proj
    - o_proj
    - gate_proj
    - down_proj
    - up_proj

model:
  name: SmolLM3-3B
  device: "cuda"
  attn_implementation: "sdpa"
  name_or_path: "HuggingFaceTB/SmolLM3-3B"
  use_bf16: true

dataset:
  name: ccat50
  name_or_path: "belati/ccat50"
  batch_size: 2 # device_batch * rescale_batch = 2 * 2 what is this for?
  max_length: 1024
  num_workers: 0

  author_id: 0
  train_samples_per_author: 10
  eval_samples_per_author: 3

training_args:
  general:
    max_grad_norm: 1.0
  sft:
    warmup_steps: 10
    max_steps: 100
    per_device_train_batch_size: 4
  dpo:
    warmup_steps: 10
    max_steps: 100
    max_length: 1024
    max_prompt_length: 512
    max_completion_length: 512
    gradient_checkpointing: true
    per_device_train_batch_size: 4

optim_args:
  sft:
    lr: 2.0e-3 # x10 because of LoRA
    weight_decay: 0.01
  dpo:
    lr: 5.0e-5 # x10 because of LoRA
    weight_decay: 0.01

sampler:
  resample_rate: 10
  frac_expert: 0.7
  frac_replay: 0.2
  frac_noisy: 0.1
  rescale_batch: 2

  gen_kwargs:
    num_return_sequences: 10
    repetition_penalty: 0.8
