defaults:
  - model: ministral-8b
  - _self_

seed: 42

hydra:
  run:
    dir: outputs/generations/${dataset.name}_${dataset.author_id}_${model.name}
  sweep:
    dir: outputs/generations
    subdir: ${dataset.name}_${dataset.author_id}_${model.name}

checkpoints:
  base_dir: outputs/models
  run_name: ${dataset.name}_${dataset.author_id}_${model.name}

dataset:
  name: ccat50
  name_or_path: belati/ccat50
  author_id: 0
  
  num_train_samples: 7
  num_eval_samples: 3

gen_kwargs:
  do_sample: true
  batch_size: 2
  num_return_sequences: 1
  max_new_tokens: 2048
  repetition_penalty: 1.2
