seed: 42

hydra:
  job:
    name: "eval_${dataset.author_id}"
  run:
    dir: outputs/generations/${dataset.name}_${dataset.author_id}_${model.name}_${estimator}

checkpoints:
  base_dir: outputs/models
  run_name: ${dataset.name}_${dataset.author_id}_${model.name}_${estimator}

dataset:
  name: ccat50
  name_or_path: belati/ccat50
  author_id: 0
  
  num_train_samples: 10
  num_eval_samples: 20

model:
  name: Ministral-8B-Instruct-2410
  name_or_path: mistralai/Ministral-8B-Instruct-2410
  device: cuda

gen_kwargs:
  do_sample: true
  batch_size: 2
  num_return_sequences: 1
  max_new_tokens: 1024
  repetition_penalty: 1.2

estimator: msp # msp, random, "None"
